//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nozhan.Utility.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrameworkValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nozhan.Utility.Core.Resources.FrameworkValidationMessages", typeof(FrameworkValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is invalid for {1}.
        /// </summary>
        public static string DataTypeFormatMismatchError {
            get {
                return ResourceManager.GetString("DataTypeFormatMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is registerd with entered email before.
        /// </summary>
        public static string EmailDuplicateError {
            get {
                return ResourceManager.GetString("EmailDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid email address.
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with the provided email in database.
        /// </summary>
        public static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequiredError {
            get {
                return ResourceManager.GetString("EmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required.
        /// </summary>
        public static string EndDateRequiredError {
            get {
                return ResourceManager.GetString("EndDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data from server!.
        /// </summary>
        public static string ErrorReadingDataFromServerError {
            get {
                return ResourceManager.GetString("ErrorReadingDataFromServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occured : {0}.
        /// </summary>
        public static string ExceptionOccuredError {
            get {
                return ResourceManager.GetString("ExceptionOccuredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required..
        /// </summary>
        public static string FieldRequiredError {
            get {
                return ResourceManager.GetString("FieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is required Error.
        /// </summary>
        public static string IdRequiredError {
            get {
                return ResourceManager.GetString("IdRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} provided for {1} is not valid..
        /// </summary>
        public static string InvalidCodingError {
            get {
                return ResourceManager.GetString("InvalidCodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for date is invalid.
        /// </summary>
        public static string InvalidDateError {
            get {
                return ResourceManager.GetString("InvalidDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered datetime is invalid.
        /// </summary>
        public static string InvalidDateTimeError {
            get {
                return ResourceManager.GetString("InvalidDateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for {0} is invalid.
        /// </summary>
        public static string InvalidFieldError {
            get {
                return ResourceManager.GetString("InvalidFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for {0} is invalid.
        /// </summary>
        public static string InvalidFormatError {
            get {
                return ResourceManager.GetString("InvalidFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for {0} is not a valid guid..
        /// </summary>
        public static string InvalidGuidError {
            get {
                return ResourceManager.GetString("InvalidGuidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid mobile number.
        /// </summary>
        public static string InvalidMobileNumberError {
            get {
                return ResourceManager.GetString("InvalidMobileNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid national code.
        /// </summary>
        public static string InvalidNationalCodeError {
            get {
                return ResourceManager.GetString("InvalidNationalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumberAttribute {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid postal code.
        /// </summary>
        public static string InvalidPostalCodeError {
            get {
                return ResourceManager.GetString("InvalidPostalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid shaba code.
        /// </summary>
        public static string InvalidShabaCodeError {
            get {
                return ResourceManager.GetString("InvalidShabaCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid shetab card number.
        /// </summary>
        public static string InvalidShetabCardError {
            get {
                return ResourceManager.GetString("InvalidShetabCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not valid for {1}.
        /// </summary>
        public static string RequiredEnumValidatorError {
            get {
                return ResourceManager.GetString("RequiredEnumValidatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found!.
        /// </summary>
        public static string SettingKeyNotFoundError {
            get {
                return ResourceManager.GetString("SettingKeyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters and maximum {1} characters long..
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters and maximum {1} characters long..
        /// </summary>
        public static string StringLengthErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} cannot be empty.
        /// </summary>
        public static string ValueCannotBeEmptyError {
            get {
                return ResourceManager.GetString("ValueCannotBeEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} cannot be null.
        /// </summary>
        public static string ValueCannotBeNullError {
            get {
                return ResourceManager.GetString("ValueCannotBeNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for {1} is outside the range of allowed value..
        /// </summary>
        public static string ValueOutOfRangeError {
            get {
                return ResourceManager.GetString("ValueOutOfRangeError", resourceCulture);
            }
        }
    }
}
